<a href="https://colab.research.google.com/github/aswathim3844/python_notes/blob/main/READING_DATA_FROM_DIFFERENT_SOURCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Reading and Handling Data from Different Sources

This notebook demonstrates how to read and handle data from various sources using the pandas library in Python.

### 1. Reading Data from Excel Files (.xlsx)

-   **`pd.read_excel(file_path, header, sheet_name)`**: This function is used to read data from Excel files.
    -   `file_path`: The path to the Excel file.
    -   `header`: Specifies the row (0-indexed) to use as the column headers.
    -   `sheet_name`: Specifies the sheet(s) to read. It can be a string (single sheet name), an integer (sheet index), a list of strings/integers, or `None` (reads all sheets into a dictionary of DataFrames).

-   **Reading all sheets**: When `sheet_name=None`, `pd.read_excel` returns a dictionary where keys are sheet names and values are DataFrames. You can access individual DataFrames using the sheet name as the key (e.g., `employees['employes']`).

-   **Concatenating DataFrames**: `pd.concat([df1, df2])` is used to combine DataFrames vertically (stacking them on top of each other). By default, it keeps the original index. Use `ignore_index=True` to reset the index.

### 2. Reading Data from CSV Files (.csv)

-   **`pd.read_csv(file_path)`**: This is the primary function for reading data from CSV files. It automatically infers delimiters in many cases.

### 3. Reading Data from XML Files (.xml)

-   **`pd.read_xml(file_path)`**: This function is used to parse XML files and load the data into a DataFrame. It requires the `lxml` library to be installed (`pip install lxml`). Ensure your XML file is well-formed.

### 4. Reading Data from JSON Files (.json)

-   **`pd.read_json(file_path)`**: This function reads data from JSON files. It can handle various JSON structures.

-   **Handling Nested Data (Exploding Lists)**: If a column contains lists (like the 'genres' column in the movies data), you can use the `.explode()` method to create a new row for each element in the list, while duplicating the values from other columns.

### 5. Reading Data from HTML Tables (.html or URL)

-   **`pd.read_html(url_or_file_path)`**: This function reads HTML tables from a URL or a local file path and returns a list of DataFrames, one for each table found.

-   **Accessing Specific Tables**: You can access individual tables from the list using their index (e.g., `tables[0]`).

-   **Combining Tables**: Similar to Excel sheets, you can use `pd.concat()` to combine multiple tables read from HTML.

### 6. Reading Data from APIs (JSON Response)

-   **Using the `requests` library**:
    -   `import requests`: Imports the library.
    -   `response = requests.get(url)`: Sends a GET request to the specified URL.
    -   `data = response.json()`: Parses the JSON response into a Python dictionary or list.

-   **Converting JSON to DataFrame**: `pd.DataFrame(data)` can directly convert a list of dictionaries (which is often the structure of a JSON API response) into a pandas DataFrame.

### 7. Data Handling and Manipulation

-   **Displaying Data**:
    -   `df.head()`: Shows the first few rows.
    -   `df.info()`: Provides a summary of the DataFrame, including column data types and non-null values.
    -   `df.shape`: Returns a tuple representing the dimensions of the DataFrame (rows, columns).
    -   `display(df)`: Provides a richer display of DataFrames in environments like Colab.

-   **Selecting Columns**: You can select one or more columns using square brackets (e.g., `df['column_name']` or `df[['col1', 'col2']]`).

-   **Filtering Data**: Use boolean indexing to filter rows based on conditions (e.g., `df[df['column'] > value]`).

-   **Grouping and Aggregating**:
    -   `df.groupby('column')`: Groups the DataFrame by unique values in a column.
    -   `.mean()`, `.count()`, `.sum()`, etc.: Apply aggregation functions to the grouped data.

-   **Sorting Data**: `df.sort_values('column', ascending=False)` sorts the DataFrame by a specific column.

-   **Renaming Columns**: `df.rename(columns={'old_name': 'new_name'}, inplace=True)` renames columns. Using `inplace=True` modifies the DataFrame directly.

-   **Merging DataFrames**: `df1.merge(df2, left_on='col1', right_on='col2', how='merge_type')` combines DataFrames based on common columns.
    -   `left_on`, `right_on`: Specify the columns to merge on in the left and right DataFrames.
    -   `how`: Specifies the type of merge ('inner', 'left', 'right', 'outer').

### Additional Tips

-   **Error Handling**: Be prepared for potential errors when reading files (e.g., `FileNotFoundError`, parsing errors). Using `try-except` blocks can make your code more robust.
-   **Data Cleaning**: Real-world data often requires cleaning (handling missing values, inconsistent formats, etc.) before analysis.
-   **Large Files**: For very large files, consider reading data in chunks to avoid memory issues.
-   **Documentation**: Refer to the pandas documentation for detailed information on all functions and methods.

In [ ]:
# Read the 'managers' sheet from the Excel file, using the second row as the header.
import pandas as pd
employees = pd.read_excel("/content/employe.xlsx",header=1,sheet_name="managers")

In [ ]:
# Display the 'employees' DataFrame.
employees

  emp_id     name   department  hire_date  salary  full_time
0  E1001  Aswathi    Marketing 2018-03-12   50000       True
1  E1002   sandra  Engineering 2019-07-23   60000       True
2  E1003  lakshmi           HR 2020-01-15   70000      False
3  E1004   nikhil      Finance 2017-11-30   80000       True
4  E1005  sakeeth        Sales 2021-05-10   90000       True

In [ ]:
# Display information about the 'employees' DataFrame, including column data types and non-null counts.
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      5 non-null      object
 1   name        5 non-null      object
 2   department  5 non-null      object
 3   hire_date   5 non-null      datetime64[ns]
 4   salary      5 non-null      int64
 5   full_time   5 non-null      bool
dtypes: bool(1), datetime64[ns](1), int64(1), object(3)
memory usage: 337.0+ bytes

In [ ]:
# Read all sheets from the Excel file into an ExcelFile object and display the sheet names.
xlsheets =pd.ExcelFile('/content/employe.xlsx')
xlsheets.sheet_names

['employes', 'managers']

In [ ]:
# Read all sheets from the Excel file into a dictionary of DataFrames.
employees = pd.read_excel("/content/employe.xlsx",header=1,sheet_name=None)
employees

{'employes':   emp_id           name   department  hire_date  salary  full_time
 0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
 1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
 2  E1003    Priya Singh           HR 2020-01-15   60000      False
 3  E1004         Li Wei      Finance 2017-11-30   79000       True
 4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True,
 'managers':   emp_id     name   department  hire_date  salary  full_time
 0  E1001  Aswathi    Marketing 2018-03-12   50000       True
 1  E1002   sandra  Engineering 2019-07-23   60000       True
 2  E1003  lakshmi           HR 2020-01-15   70000      False
 3  E1004   nikhil      Finance 2017-11-30   80000       True
 4  E1005  sakeeth        Sales 2021-05-10   90000       True}

In [ ]:
# Access and display the 'employes' sheet DataFrame.
data1=employees['employes']
data1

  emp_id           name   department  hire_date  salary  full_time
0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
2  E1003    Priya Singh           HR 2020-01-15   60000      False
3  E1004         Li Wei      Finance 2017-11-30   79000       True
4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True

In [ ]:
# Access and display the 'managers' sheet DataFrame.
data2=employees['managers']
data2

  emp_id     name   department  hire_date  salary  full_time
0  E1001  Aswathi    Marketing 2018-03-12   50000       True
1  E1002   sandra  Engineering 2019-07-23   60000       True
2  E1003  lakshmi           HR 2020-01-15   70000      False
3  E1004   nikhil      Finance 2017-11-30   80000       True
4  E1005  sakeeth        Sales 2021-05-10   90000       True

In [ ]:
# Concatenate the 'employes' and 'managers' DataFrames.
data=pd.concat([data1,data2])
data

  emp_id           name   department  hire_date  salary  full_time
0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
2  E1003    Priya Singh           HR 2020-01-15   60000      False
3  E1004         Li Wei      Finance 2017-11-30   79000       True
4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True
0  E1001        Aswathi    Marketing 2018-03-12   50000       True
1  E1002         sandra  Engineering 2019-07-23   60000       True
2  E1003        lakshmi           HR 2020-01-15   70000      False
3  E1004         nikhil      Finance 2017-11-30   80000       True
4  E1005        sakeeth        Sales 2021-05-10   90000       True

In [ ]:
# Filter the concatenated DataFrame to show only full-time employees.
full_time_employees = data[data['full_time']== True]
full_time_employees

  emp_id           name   department  hire_date  salary  full_time
0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
3  E1004         Li Wei      Finance 2017-11-30   79000       True
4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True
0  E1001        Aswathi    Marketing 2018-03-12   50000       True
1  E1002         sandra  Engineering 2019-07-23   60000       True
3  E1004         nikhil      Finance 2017-11-30   80000       True
4  E1005        sakeeth        Sales 2021-05-10   90000       True

In [ ]:
# Calculate the average salary for each department in the concatenated DataFrame.
average_salary=data.groupby("department")["salary"].mean()
average_salary

department
Engineering    72500.0
Finance        79500.0
HR             65000.0
Marketing      61000.0
Sales          78500.0
Name: salary, dtype: float64

In [ ]:
# Save the concatenated DataFrame to a new Excel file named 'new_data.xlsx' without the index.
data.to_excel('new_data.xlsx',index=False)

In [ ]:
# Save the concatenated DataFrame to a new Excel file named 'new_data1.xlsx' with the index.
data.to_excel('new_data1.xlsx',index=True)

In [ ]:
# Read data from a CSV file named 'weather.csv' into a DataFrame.
df=pd.read_csv("/content/weather.csv")
df

,date,station_id,temperature_c,humidity_pct,wind_speed_kmh,precip_mm
0,2025-07-01,WS100,29.5,65,12.4,0.0
1,2025-07-01,WS101,31.2,58,8.7,0.0
2,2025-07-01,WS102,28.9,72,5.2,1.3
3,2025-07-02,WS100,30.1,63,14.0,0.0
4,2025-07-02,WS101,32.0,55,10.1,0.0
5,2025-07-02,WS102,29.5,70,6.0,0.8
6,2025-07-03,WS100,28.0,68,11.3,2.5
7,2025-07-03,WS101,29.8,60,9.5,0.0
8,2025-07-03,WS102,27.7,75,4.8,3.1

In [ ]:
# Filter the weather DataFrame to show only rows where the temperature is greater than 30 degrees Celsius.
temperature=df[df['temperature_c']>30]
temperature

,date,station_id,temperature_c,humidity_pct,wind_speed_kmh,precip_mm
1,2025-07-01,WS101,31.2,58,8.7,0.0
3,2025-07-02,WS100,30.1,63,14.0,0.0
4,2025-07-02,WS101,32.0,55,10.1,0.0

In [ ]:
# Calculate the average humidity for each date in the weather DataFrame.
avg_humidity=df.groupby('date')['humidity_pct'].mean()
avg_humidity

date
2025-07-01    65.000000
2025-07-02    62.666667
2025-07-03    67.666667
Name: humidity_pct, dtype: float64

In [ ]:

# Read data from an XML file named 'library_catalog.xml' into a DataFrame.
library=pd.read_xml('/content/library_catalog.xml')
library

,isbn,title,author,genre,publish_date,price
0,978-0143127550,The Martian,Andy Weir,Science Fiction,2014-10-28,9.99
1,978-0553386790,"Thinking, Fast and Slow",Daniel Kahneman,Psychology,2013-04-02,12.50
2,978-0062316097,The Alchemist,Paulo Coelho,Fiction,2014-04-15,8.99

In [ ]:
# Select and display the 'genre' column from the library DataFrame.
genres=library['genre']
genres

0    Science Fiction
1         Psychology
2            Fiction
Name: genre, dtype: object

In [ ]:
# Read data from a JSON file named 'movies.json' into a DataFrame.
movies=pd.read_json("/content/movies.json")
movies

,movie_id,title,year,genres,rating,votes
0,MV001,Inception,2010,"[Action, Sci‐Fi]",8.8,2100000
1,MV002,The Dark Knight,2008,"[Action, Crime, Drama]",9.0,2300000
2,MV003,Interstellar,2014,"[Adventure, Drama, Sci‐Fi]",8.6,1500000
3,MV004,The Matrix,1999,"[Action, Sci‐Fi]",8.7,1700000
4,MV005,Parasite,2019,"[Comedy, Drama, Thriller]",8.6,700000
5,MV006,Gladiator,2000,"[Action, Adventure, Drama]",8.5,1400000
6,MV007,Avengers: Endgame,2019,"[Action, Adventure, Drama]",8.4,1000000
7,MV008,The Shawshank Redemption,1994,[Drama],9.3,2400000
8,MV009,Pulp Fiction,1994,"[Crime, Drama]",8.9,1800000
9,MV010,Forrest Gump,1994,"[Drama, Romance]",8.8,1900000

In [ ]:
# Merge the selected launch and rocket DataFrames using a left merge on 'rocket_id' and 'id'.
data=df1_final.merge(rockets,left_on='rocket_id',right_on='id',how='left')
data

,machine_name,date_utc,success,details,rocket_id,launch_library_id,name,cost_per_launch,company,country,id
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
...,...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,Falcon 9,50000000,SpaceX,United States,5e9d0d95eda69973a809d1ec
201,TTL-1,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,Falcon 9,50000000,SpaceX,United States,5e9d0d95eda69973a809d1ec
202,WorldView Legion 1 & 2,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,Falcon 9,50000000,SpaceX,United States,5e9d0d95eda69973a809d1ec
203,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed,None,Falcon Heavy,90000000,SpaceX,United States,5e9d0d95eda69974db09d1ed
204,O3b mPower 3.4,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,Falcon 9,50000000,SpaceX,United States,5e9d0d95eda69973a809d1ec

In [ ]:
# Sort the movies DataFrame by 'rating' in descending order and display the top 1 row.
movies.sort_values('rating',ascending=False).head(1)

  movie_id                     title  year   genres  rating    votes
7    MV008  The Shawshank Redemption  1994  [Drama]     9.3  2400000

In [ ]:
# Explode the 'genres' list in the movies DataFrame to have one genre per row.
movie_genre =movies.explode('genres')
movie_genre

  movie_id                     title  year     genres  rating    votes
0    MV001                 Inception  2010     Action     8.8  2100000
0    MV001                 Inception  2010     Sci‐Fi     8.8  2100000
1    MV002           The Dark Knight  2008     Action     9.0  2300000
1    MV002           The Dark Knight  2008      Crime     9.0  2300000
1    MV002           The Dark Knight  2008      Drama     9.0  2300000
2    MV003              Interstellar  2014  Adventure     8.6  1500000
2    MV003              Interstellar  2014      Drama     8.6  1500000
2    MV003              Interstellar  2014     Sci‐Fi     8.6  1500000
3    MV004                The Matrix  1999     Action     8.7  1700000
3    MV004                The Matrix  1999     Sci‐Fi     8.7  1700000
4    MV005                  Parasite  2019     Comedy     8.6   700000
4    MV005                  Parasite  2019      Drama     8.6   700000
4    MV005                  Parasite  2019   Thriller     8.6   700000
5    MV006                 Gladiator  2000     Action     8.5  1400000
5    MV006                 Gladiator  2000  Adventure     8.5  1400000
5    MV006                 Gladiator  2000      Drama     8.5  1400000
6    MV007         Avengers: Endgame  2019     Action     8.4  1000000
6    MV007         Avengers: Endgame  2019  Adventure     8.4  1000000
6    MV007         Avengers: Endgame  2019      Drama     8.4  1000000
7    MV008  The Shawshank Redemption  1994      Drama     9.3  2400000
8    MV009              Pulp Fiction  1994      Crime     8.9  1800000
8    MV009              Pulp Fiction  1994      Drama     8.9  1800000
9    MV010              Forrest Gump  1994      Drama     8.8  1900000
9    MV010              Forrest Gump  1994    Romance     8.8  1900000

In [ ]:

# Calculate the average rating for each genre in the exploded movie DataFrame.
avg_ratings=movie_genre.groupby('genres')['rating'].mean()
avg_ratings

genres
Action       8.6800
Adventure    8.5000
Comedy       8.6000
Crime        8.9500
Drama        8.7625
Romance      8.8000
Sci‐Fi       8.7000
Thriller     8.6000
Name: rating, dtype: float64

In [ ]:
# Count the number of movies released in each year.
count_year=movies.groupby('year')['year'].count()
count_year

year
1994    3
1999    1
2000    1
2008    1
2010    1
2014    1
2019    2
Name: year, dtype: int64

In [ ]:
# Read tables from an HTML file named 'review.html' into a list of DataFrames.
review=pd.read_html("/content/review.html")
review

[  review_id reviewer     restaurant  rating                         comment  \
 0      R001    Alice  The Spice Hub     4.5   Great flavors but a bit loud.
 1      R002      Bob    Sushi World     5.0    Fresh fish and perfect rice.
 2      R003     Chen   Pasta Palace     4.0  Cozy place, generous portions.

          date
 0  2025-06-20
 1  2025-06-22
 2  2025-06-25  ]

In [ ]:
# Display the number of tables read from the HTML file.
len(review)

1

In [ ]:
# Display the number of rows in the first DataFrame from the list of tables.
review[0].shape[0]

3

In [ ]:
# Access the DataFrame from the list
df_review = review[0]

# Now filter the DataFrame
rating = df_review[df_review['rating'] > 4.5]
display(rating)

,review_id,reviewer,restaurant,rating,comment,date
1,R002,Bob,Sushi World,5.0,Fresh fish and perfect rice.,2025-06-22

In [ ]:
# Filter the first DataFrame from the list of tables to show reviews with a rating greater than 4.5.
ratings=review[0][review[0]['rating']>4.5]
ratings

,review_id,reviewer,restaurant,rating,comment,date
1,R002,Bob,Sushi World,5.0,Fresh fish and perfect rice.,2025-06-22

In [ ]:
# Define the URL for the COVID-19 countries data API.
import requests
url='https://disease.sh/v3/covid-19/countries'

# Send a GET request to the API and parse the JSON response.
response=requests.get(url)
data=response.json()
#data

# Convert the JSON data into a DataFrame and display the first few rows.
covid_df=pd.DataFrame(data)
covid_df.head()

,updated,country,countryInfo,cases,todayCases,deaths,todayDeaths,recovered,todayRecovered,active,...,tests,testsPerOneMillion,population,continent,oneCasePerPeople,oneDeathPerPeople,oneTestPerPeople,activePerOneMillion,recoveredPerOneMillion,criticalPerOneMillion
0,1758866705149,Afghanistan,"{'_id': 4, 'iso2': 'AF', 'iso3': 'AFG', 'lat':...",234174,0,7996,0,211080,0,15098,...,1390730,34125,40754388,Asia,174,5097,29,370.46,5179.32,0.0
1,1758866705141,Albania,"{'_id': 8, 'iso2': 'AL', 'iso3': 'ALB', 'lat':...",334863,0,3605,0,330233,0,1025,...,1941032,677173,2866374,Europe,9,795,1,357.59,115209.32,0.0
2,1758866705144,Algeria,"{'_id': 12, 'iso2': 'DZ', 'iso3': 'DZA', 'lat'...",272010,0,6881,0,183061,0,82068,...,230960,5093,45350148,Africa,167,6591,196,1809.65,4036.61,0.0
3,1758866705199,Andorra,"{'_id': 20, 'iso2': 'AD', 'iso3': 'AND', 'lat'...",48015,0,165,0,0,0,47850,...,249838,3225256,77463,Europe,2,469,0,617714.26,0.00,0.0
4,1758866705178,Angola,"{'_id': 24, 'iso2': 'AO', 'iso3': 'AGO', 'lat'...",107327,0,1937,0,103419,0,1971,...,1499795,42818,35027343,Africa,326,18083,23,56.27,2952.52,0.0

In [ ]:
# Display the shape (number of rows and columns) of the COVID-19 DataFrame.
covid_df.shape

(231, 23)

In [ ]:
# Display information about the COVID-19 DataFrame, including column data types and non-null counts.
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   updated                 231 non-null    int64
 1   country                 231 non-null    object
 2   countryInfo             231 non-null    object
 3   cases                   231 non-null    int64
 4   todayCases              231 non-null    int64
 5   deaths                  231 non-null    int64
 6   todayDeaths             231 non-null    int64
 7   recovered               231 non-null    int64
 8   todayRecovered          231 non-null    int64
 9   active                  231 non-null    int64
 10  critical                231 non-null    int64
 11  casesPerOneMillion      231 non-null    int64
 12  deathsPerOneMillion     231 non-null    int64
 13  tests                   231 non-null    int64
 14  testsPerOneMillion      231 non-null    int64
 15  population              231 non-null    int64
 16  continent               231 non-null    object
 17  oneCasePerPeople        231 non-null    int64
 18  oneDeathPerPeople       231 non-null    int64
 19  oneTestPerPeople        231 non-null    int64
 20  activePerOneMillion     231 non-null    float64
 21  recoveredPerOneMillion  231 non-null    float64
 22  criticalPerOneMillion   231 non-null    float64
dtypes: float64(3), int64(17), object(3)
memory usage: 41.6+ KB

In [ ]:
# Select and display specific columns from the COVID-19 DataFrame.
covid_info = covid_df[['country','cases','deaths','critical','active','recovered']]
covid_info

               country   cases  deaths  critical  active  recovered
0          Afghanistan  234174    7996         0   15098     211080
1              Albania  334863    3605         0    1025     330233
2              Algeria  272010    6881         0   82068     183061
3              Andorra   48015     165         0   47850          0
4               Angola  107327    1937         0    1971     103419
..                 ...     ...     ...       ...     ...        ...
226  Wallis and Futuna    3550       8         0    3104        438
227     Western Sahara      10       1         0       0          9
228              Yemen   11945    2159         0     662       9124
229             Zambia  349304    4069         0    3919     341316
230           Zimbabwe  266359    5740        12    1731     258888

[231 rows x 6 columns]

In [ ]:
# Save the selected COVID-19 information DataFrame to an Excel file named 'cov_info.xlsx' without the index.
covid_info.to_excel('cov_info.xlsx',index=False)

In [ ]:
# Define the URL for the fastest marathoners and courses data.
url='https://www.runnersworld.com/races-places/a20823734/these-are-the-worlds-fastest-marathoners-and-marathon-courses/'

# Read tables from the URL into a list of DataFrames.
tables=pd.read_html(url)
# Print the number of tables found on the page.
print(len(tables))

8

In [ ]:
# Display the list of DataFrames read from the URL.
tables

[                             0            1          2               3
 0                       Runner  Finish Time  Pace/Mile        Marathon
 1        Kelvin Kiptum (Kenya)      2:00:35     4:36.0   Chicago, 2023
 2       Eliud Kipchoge (Kenya)      2:01:09     4:37.2    Berlin, 2022
 3   Kenenisa Bekele (Ethiopia)      2:01:41     4:38.5    Berlin, 2019
 4       Sisay Lemma (Ethiopia)      2:01:48     4:38.7  Valencia, 2023
 5       Sabastian Sawe (Kenya)      2:02:05     4:39.4  Valencia, 2024
 6       Benson Kipruto (Kenya)      2:02:16     4:39.8     Tokyo, 2024
 7     Deresa Geleta (Ethiopia)      2:02:38     4:40.6  Valencia, 2024
 8           John Korir (Kenya)      2:02:44     4:40.8   Chicago, 2024
 9    Birhanu Legese (Ethiopia)      2:02:48     4:41.0    Berlin, 2019
 10  Mosinet Geremew (Ethiopia)      2:02:55     4:41.3    London, 2019,
                                   0            1          2               3
 0                            Runner  Finish Time  Pace/Mile        Marathon
 1          Ruth Chepngetich (Kenya)      2:09:56     4:57.4   Chicago, 2024
 2          Tigist Assefa (Ethiopia)      2:11:53     5:01.8    Berlin, 2023
 3        Sifan Hassan (Netherlands)      2:13:44     5:06.0   Chicago, 2023
 4             Brigid Kosgei (Kenya)      2:14:04     5:06.8   Chicago, 2019
 5                               NaN          NaN        NaN             NaN
 6           Amane Beriso (Ethiopia)      2:14:58     5:08.9  Valencia, 2022
 7   Paula Radcliffe (Great Britain)      2:15:25     5:09.9    London, 2003
 8        Worknesh Degefa (Ethiopia)      2:15:51     5:10.9  Valencia, 2023
 9          Sutume Kebede (Ethiopia)      2:15:55     5:11.0     Tokyo, 2024
 10         Tigist Ketema (Ethiopia)      2:16:07     5:11.5     Dubai, 2024
 11         Rosemary Wanjiru (Kenya)      2:16:14     5:11.8     Tokyo, 2024
 12                              NaN          NaN        NaN             NaN,
                     0            1          2                 3
 0              Runner  Finish Time  Pace/Mile          Marathon
 1   Khalid Khannouchi      2:05:38     4:47.5      London, 2002
 2          Galen Rupp      2:06:07     4:48.6      Prague, 2018
 3           Ryan Hall      2:06:17     4:49.0      London, 2008
 4       Biya Simbassa      2:06:53     4:50.4    Valencia, 2024
 5   Dathan Ritzenhein      2:07:47     4:52.4     Chicago, 2012
 6        Conner Mantz      2:07:47     4:52.4     Chicago, 2023
 7       Leonard Korir      2:07:56     4:52.8   Amsterdam, 2019
 8       Clayton Young      2:08:00     4:52.9     Chicago, 2023
 9        CJ Albertson      2:08:17     4:53.6     Chicago, 2024
 10         Alex Maier      2:08:33     4:54.2  Dusseldorf, 2025,
                    0            1          2                           3
 0             Runner  Finish Time  Pace/Mile                    Marathon
 1       Emily Sisson      2:18:29     5:16.9               Chicago, 2022
 2      Keira D’Amato      2:19:12     5:18.6               Houston, 2022
 3        Betsy Saina      2:19:17     5:18.7                 Tokyo, 2024
 4       Deena Kastor      2:19:36     5:19.5                London, 2006
 5          Sara Hall      2:20:32     5:21.6  The Marathon Project, 2020
 6       Jordan Hasay      2:20:57     5:22.6               Chicago, 2017
 7   Shalane Flanagan      2:21:14     5:23.2                Berlin, 2014
 8     Joan Samuelson      2:21:21     5:23.5               Chicago, 1985
 9          Amy Cragg      2:21:42     5:24.3                 Tokyo, 2018
 10  Susanna Sullivan      2:21:56     5:24.8               Chicago, 2024,
                              0            1          2               3
 0                       Runner  Finish Time  Pace/Mile        Marathon
 1        Kelvin Kiptum (Kenya)      2:00:35     4:36.0   Chicago, 2023
 2       Eliud Kipchoge (Kenya)      2:01:09     4:37.2    Berlin, 2022
 3        Kelvin Kiptum (Kenya)      2:01:25     4:37.8    London, 2023
 4       Eliud Kipchoge (Kenya)      2:01:39     4:38.4    Berlin, 2018
 5   Kenenisa Bekele (Ethiopia)      2:01:41     4:38.5    Berlin, 2019
 6       Sisay Lemma (Ethiopia)      2:01:48     4:38.7  Valencia, 2023
 7        Kelvin Kiptum (Kenya)      2:01:53     4:38.9  Valencia, 2022
 8       Sabastian Sawe (Kenya)      2:02:05     4:39.4  Valencia, 2024
 9       Benson Kipruto (Kenya)      2:02:16     4:39.8     Tokyo, 2024
 10      Sabastian Sawe (Kenya)      2:02:16     4:39.8    Berlin, 2025
 11                         NaN          NaN        NaN             NaN,
                                   0            1          2               3
 0                            Runner  Finish Time  Pace/Mile        Marathon
 1          Ruth Chepngetich (Kenya)      2:09:56     4:57.4   Chicago, 2024
 2          Tigist Assefa (Ethiopia)      2:11:53     5:01.8    Berlin, 2023
 3        Sifan Hassan (Netherlands)      2:13:44     5:06.0   Chicago, 2023
 4             Brigid Kosgei (Kenya)      2:14:04     5:06.8   Chicago, 2019
 5          Ruth Chepngetich (Kenya)      2:14:18     5:07.3   Chicago, 2022
 6           Amane Beriso (Ethiopia)      2:14:58     5:08.9  Valencia, 2022
 7   Paula Radcliffe (Great Britain)      2:15:25     5:09.9    London, 2003
 8          Tigist Assefa (Ethiopia)      2:15:37     5:10.3    Berlin, 2022
 9          Ruth Chepngetich (Kenya)      2:15:37     5:10.3   Chicago, 2023
 10         Tigist Assefa (Ethiopia)      2:15:50     5:10.8    London, 2025,
                                     0            1          2                3
 0                              Runner  Finish Time  Pace/Mile         Marathon
 1         Belayneh Densamo (Ethiopia)      2:06:50     4:50.3  Rotterdam, 1988
 2           Ronaldo da Costa (Brazil)      2:06:06     4:48.6     Berlin, 1998
 3         Khalid Khannouchi (Morocco)      2:05:42     4:47.7    Chicago, 1999
 4   Khalid Khannouchi (United States)      2:05:38     4:47.5     London, 2002
 5                 Paul Tergat (Kenya)      2:04:55     4:45.9     Berlin, 2003
 6       Haile Gebrselassie (Ethiopia)      2:04:26     4:44.8     Berlin, 2007
 7       Haile Gebrselassie (Ethiopia)      2:03:59     4:43.8     Berlin, 2008
 8               Patrick Makau (Kenya)      2:03:38     4:43.0     Berlin, 2011
 9              Wilson Kipsang (Kenya)      2:03:23     4:42.4     Berlin, 2013
 10             Dennis Kimetto (Kenya)      2:02:57     4:41.4     Berlin, 2014
 11             Eliud Kipchoge (Kenya)      2:01:39     4:38.4     Berlin, 2018
 12             Eliud Kipchoge (Kenya)      2:01:09     4:37.2     Berlin, 2022
 13              Kelvin Kiptum (Kenya)      2:00:35     4:36.0    Chicago, 2023,
                                  0            1          2                3
 0                           Runner  Finish Time  Pace/Mile         Marathon
 1            Tegla Loroupe (Kenya)      2:20:47     5:22.2  Rotterdam, 1998
 2            Tegla Loroupe (Kenya)      2:20:43     5:22.0     Berlin, 1999
 3          Naoko Takahashi (Japan)      2:19:46     5:19.8     Berlin, 2001
 4        Catherine Ndereba (Kenya)      2:18:47     5:17.6    Chicago, 2001
 5  Paula Radcliffe (Great Britain)      2:17:18     5:14.2    Chicago, 2002
 6  Paula Radcliffe (Great Britain)      2:15:25     5:09.9     London, 2003
 7            Brigid Kosgei (Kenya)      2:14:04     5:06.8    Chicago, 2019
 8         Tigist Assefa (Ethiopia)      2:11:53     5:01.8     Berlin, 2023
 9         Ruth Chepngetich (Kenya)      2:09:56     4:47.4    Chicago, 2024]

In [ ]:
# Combine all tables into one, skipping headers after the first
combined_df = tables[0]  # Start with the first table (keep its header)

for table in tables[1:]:
    combined_df = pd.concat([combined_df, table], ignore_index=True)

combined_df.head(20)

                                  0            1          2               3
0                            Runner  Finish Time  Pace/Mile        Marathon
1             Kelvin Kiptum (Kenya)      2:00:35     4:36.0   Chicago, 2023
2            Eliud Kipchoge (Kenya)      2:01:09     4:37.2    Berlin, 2022
3        Kenenisa Bekele (Ethiopia)      2:01:41     4:38.5    Berlin, 2019
4            Sisay Lemma (Ethiopia)      2:01:48     4:38.7  Valencia, 2023
5            Sabastian Sawe (Kenya)      2:02:05     4:39.4  Valencia, 2024
6            Benson Kipruto (Kenya)      2:02:16     4:39.8     Tokyo, 2024
7          Deresa Geleta (Ethiopia)      2:02:38     4:40.6  Valencia, 2024
8                John Korir (Kenya)      2:02:44     4:40.8   Chicago, 2024
9         Birhanu Legese (Ethiopia)      2:02:48     4:41.0    Berlin, 2019
10       Mosinet Geremew (Ethiopia)      2:02:55     4:41.3    London, 2019
11                           Runner  Finish Time  Pace/Mile        Marathon
12         Ruth Chepngetich (Kenya)      2:09:56     4:57.4   Chicago, 2024
13         Tigist Assefa (Ethiopia)      2:11:53     5:01.8    Berlin, 2023
14       Sifan Hassan (Netherlands)      2:13:44     5:06.0   Chicago, 2023
15            Brigid Kosgei (Kenya)      2:14:04     5:06.8   Chicago, 2019
16                              NaN          NaN        NaN             NaN
17          Amane Beriso (Ethiopia)      2:14:58     5:08.9  Valencia, 2022
18  Paula Radcliffe (Great Britain)      2:15:25     5:09.9    London, 2003
19       Worknesh Degefa (Ethiopia)      2:15:51     5:10.9  Valencia, 2023

In [ ]:
# Concatenate all DataFrames from the list, ignoring the original index, and display the first 20 rows.
new_table = pd.concat(tables,ignore_index=True).head(20)
display(new_table)

                                  0            1          2               3
0                            Runner  Finish Time  Pace/Mile        Marathon
1             Kelvin Kiptum (Kenya)      2:00:35     4:36.0   Chicago, 2023
2            Eliud Kipchoge (Kenya)      2:01:09     4:37.2    Berlin, 2022
3        Kenenisa Bekele (Ethiopia)      2:01:41     4:38.5    Berlin, 2019
4            Sisay Lemma (Ethiopia)      2:01:48     4:38.7  Valencia, 2023
5            Sabastian Sawe (Kenya)      2:02:05     4:39.4  Valencia, 2024
6            Benson Kipruto (Kenya)      2:02:16     4:39.8     Tokyo, 2024
7          Deresa Geleta (Ethiopia)      2:02:38     4:40.6  Valencia, 2024
8                John Korir (Kenya)      2:02:44     4:40.8   Chicago, 2024
9         Birhanu Legese (Ethiopia)      2:02:48     4:41.0    Berlin, 2019
10       Mosinet Geremew (Ethiopia)      2:02:55     4:41.3    London, 2019
11                           Runner  Finish Time  Pace/Mile        Marathon
12         Ruth Chepngetich (Kenya)      2:09:56     4:57.4   Chicago, 2024
13         Tigist Assefa (Ethiopia)      2:11:53     5:01.8    Berlin, 2023
14       Sifan Hassan (Netherlands)      2:13:44     5:06.0   Chicago, 2023
15            Brigid Kosgei (Kenya)      2:14:04     5:06.8   Chicago, 2019
16                              NaN          NaN        NaN             NaN
17          Amane Beriso (Ethiopia)      2:14:58     5:08.9  Valencia, 2022
18  Paula Radcliffe (Great Britain)      2:15:25     5:09.9    London, 2003
19       Worknesh Degefa (Ethiopia)      2:15:51     5:10.9  Valencia, 2023

In [ ]:
# Define the URL for the SpaceX launches API.
import requests
url_1='https://api.spacexdata.com/v4/launches'

# Send a GET request to the API and parse the JSON response.
response=requests.get(url_1)
df1=response.json()

# Convert the JSON data into a DataFrame and display the first few rows.
launch_df=pd.DataFrame(df1)
launch_df.head()

,fairings,links,static_fire_date_utc,static_fire_date_unix,net,window,rocket,success,failures,details,...,date_utc,date_unix,date_local,date_precision,upcoming,cores,auto_update,tbd,launch_library_id,id
0,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2006-03-17T00:00:00.000Z,1.142554e+09,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",Engine failure at 33 seconds and loss of vehicle,...,2006-03-24T22:30:00.000Z,1143239400,2006-03-25T10:30:00+12:00,hour,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",True,False,None,5eb87cd9ffd86e000604b32a
1,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",Successful first stage burn and transition to ...,...,2007-03-21T01:10:00.000Z,1174439400,2007-03-21T13:10:00+12:00,hour,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",True,False,None,5eb87cdaffd86e000604b32b
2,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",Residual stage 1 thrust led to collision betwe...,...,2008-08-03T03:34:00.000Z,1217734440,2008-08-03T15:34:00+12:00,hour,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",True,False,None,5eb87cdbffd86e000604b32c
3,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2008-09-20T00:00:00.000Z,1.221869e+09,False,0.0,5e9d0d95eda69955f709d1eb,True,[],Ratsat was carried to orbit on the first succe...,...,2008-09-28T23:15:00.000Z,1222643700,2008-09-28T11:15:00+12:00,hour,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",True,False,None,5eb87cdbffd86e000604b32d
4,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,True,[],None,...,2009-07-13T03:35:00.000Z,1247456100,2009-07-13T15:35:00+12:00,hour,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",True,False,None,5eb87cdcffd86e000604b32e

In [ ]:
# Select and display specific columns from the launch DataFrame.
df1_selected=launch_df[['name','date_utc','success','details','rocket','launch_library_id']]
df1_selected

,name,date_utc,success,details,rocket,launch_library_id
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,None
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,None
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,None
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,None
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb,None
...,...,...,...,...,...,...
200,Transporter-6,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
201,TTL-1,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
202,WorldView Legion 1 & 2,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
203,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed,None
204,O3b mPower 3.4,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None

In [ ]:
# Rename columns in the selected launch DataFrame and display the first few rows.
df1_final=df1_selected
df1_selected.rename(columns={'name': 'machine_name', 'rocket': 'rocket_id'}, inplace=True)
display(df1_selected.head())

/tmp/ipython-input-2574165428.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_selected.rename(columns={'name': 'machine_name', 'rocket': 'rocket_id'}, inplace=True)

,machine_name,date_utc,success,details,rocket_id,launch_library_id
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,None
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,None
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,None
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,None
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb,None

In [ ]:
# Define the URL for the SpaceX rockets API.
url_2='https://api.spacexdata.com/v4/rockets'

# Send a GET request to the API and parse the JSON response.
response=requests.get(url_2)
df2=response.json()

# Convert the JSON data into a DataFrame and display the column names.
rocket_df=pd.DataFrame(df2)
rocket_df.columns

Index(['height', 'diameter', 'mass', 'first_stage', 'second_stage', 'engines',
       'landing_legs', 'payload_weights', 'flickr_images', 'name', 'type',
       'active', 'stages', 'boosters', 'cost_per_launch', 'success_rate_pct',
       'first_flight', 'country', 'company', 'wikipedia', 'description', 'id'],
      dtype='object')

In [ ]:
# Select and display specific columns from the rocket DataFrame.
rockets=rocket_df[['name','cost_per_launch','company','country','id']]
rockets

,name,cost_per_launch,company,country,id
0,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
1,Falcon 9,50000000,SpaceX,United States,5e9d0d95eda69973a809d1ec
2,Falcon Heavy,90000000,SpaceX,United States,5e9d0d95eda69974db09d1ed
3,Starship,7000000,SpaceX,United States,5e9d0d96eda699382d09d1ee

In [ ]:
# Merge the selected launch and rocket DataFrames using a right merge on 'rocket_id' and 'id'.
data_inner=df1_final.merge(rockets,left_on='rocket_id',right_on='id',how='right')
data_inner

,machine_name,date_utc,success,details,rocket_id,launch_library_id,name,cost_per_launch,company,country,id
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb,None,Falcon 1,6700000,SpaceX,Republic of the Marshall Islands,5e9d0d95eda69955f709d1eb
...,...,...,...,...,...,...,...,...,...,...,...
201,ArabSat 6A,2019-04-11T22:35:00.000Z,True,SpaceX will launch Arabsat 6A to a geostationa...,5e9d0d95eda69974db09d1ed,None,Falcon Heavy,90000000,SpaceX,United States,5e9d0d95eda69974db09d1ed
202,STP-2,2019-06-25T03:30:00.000Z,True,Space Test Program 2 is a rideshare managed by...,5e9d0d95eda69974db09d1ed,None,Falcon Heavy,90000000,SpaceX,United States,5e9d0d95eda69974db09d1ed
203,USSF-44,2022-11-01T13:41:00.000Z,None,None,5e9d0d95eda69974db09d1ed,2306e0bc-e1a3-4a4a-9285-e1a94073655e,Falcon Heavy,90000000,SpaceX,United States,5e9d0d95eda69974db09d1ed
204,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed,None,Falcon Heavy,90000000,SpaceX,United States,5e9d0d95eda69974db09d1ed
205,NaN,NaN,NaN,NaN,NaN,NaN,Starship,7000000,SpaceX,United States,5e9d0d96eda699382d09d1ee

In [ ]:
# Merge the selected launch and rocket DataFrames using an inner merge on 'rocket_id' and 'id', and display the shape of the resulting DataFrame.
data=df1_final.merge(rockets,left_on='rocket_id',right_on='id',how='inner')
data.shape

(205, 11)